# .github/workflows/check-master-sync.yml
name: Main pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    needs: check-sync
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
      - name: Restore dependencies
        run: dotnet restore ./backend/Swen3.API/Swen3.API.csproj
      - name: Build the project
        run: dotnet build ./backend/Swen3.API/Swen3.API.csproj --no-restore
      - name: Run unit tests
        run: dotnet test ./backend/Swen3.Tests/Swen3.Tests.csproj --no-build --verbosity normal
