name: Main pipeline

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      runTests:
        description: 'Run unit tests'
        required: true
        default: 'true'

jobs:
  unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
      - name: Restore dependencies
        run: dotnet restore ./Backend/Swen3.API.csproj
      - name: Build the project
        run: dotnet build ./Backend/Swen3.API.csproj --no-restore
      - name: Run unit tests
        if: ${{ github.event_name != 'workflow_dispatch' || github.event.inputs.runTests == 'true' }}
        run: dotnet test ./Swen3Tests/Swen3Tests.csproj --no-build --verbosity normal
